# Build: docker build -f Dockerfile.artifact-poetry -t any-artifact-poetry:latest $(mktemp -d)
FROM python:3.11

ENV VENV_PATH=/tmp/venv
ENV PATH=$VENV_PATH/bin:$PATH

RUN mkdir "$VENV_PATH" \
    && python3 -m venv "$VENV_PATH" \
    && "$VENV_PATH/bin/pip" install -U pip setuptools \
    && "$VENV_PATH/bin/pip" install poetry

WORKDIR /app

ENTRYPOINT ["bash", "-c", "poetry install && poetry build --format wheel"]
