FROM python:3.11

ARG IMAGE_NAME
ENV IMAGE_NAME=${IMAGE_NAME}

WORKDIR /app

# dependencies
COPY dist/requirements.txt /app/dist/requirements.txt
RUN pip install -r /app/dist/requirements.txt

# project
COPY dist/"$IMAGE_NAME"*.whl /app/dist/
RUN pip install /app/dist/"$IMAGE_NAME"*.whl

ENTRYPOINT ["python", "-m", "$IMAGE_NAME"]
