FROM python:3.11

WORKDIR /app

# dependencies
COPY dist/requirements.txt /app/dist/requirements.txt
RUN pip install -r /app/dist/requirements.txt

# project
COPY dist/*.whl /app/dist/
COPY bin /app/bin
RUN pip install /app/dist/*.whl

ENTRYPOINT ["bin/run"]
