FROM python:3.11

# --- dependencies
WORKDIR /app
ADD lib /app/lib
ENV PYTHONPATH=/app/lib/python3.11/site-packages/:$PYTHONPATH

# --- project
ARG PYTHON_MODULE
ENV PYTHON_MODULE=${PYTHON_MODULE}
ADD dist/*.whl /app/dist/
RUN bash -c "python -m pip install --no-dependencies /app/dist/*.whl"
RUN echo "python -m $PYTHON_MODULE" > "/app/entrypoint.sh"

ENTRYPOINT ["bash", "/app/entrypoint.sh"]
