apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: installations.release-engineers.com
spec:
  scope: Namespaced
  group: release-engineers.com
  names:
    kind: Installation
    plural: installations
    singular: installation
    shortNames:
      - inst
      - insts
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                repository:
                  type: string
                branch:
                  type: string
                commit:
                  type: string
                namespace:
                  type: string
