# Build:
#  docker build -f any/resources/Dockerfile.image-poetry -t $project:$commit $project
FROM python:3.11-alpine

RUN apk add --no-cache unzip

WORKDIR /app

ENV PYTHONPATH=/app/lib/python3.11/site-packages/:$PYTHONPATH

ADD .venv/lib/ /app/lib
ADD dist/*.whl /app/dist/

RUN unzip -n -q /app/dist/*.whl -d /app/lib/python3.11/site-packages/

ENTRYPOINT ["sh", "-c", "python -m $(cd /app/dist && ls *.whl | cut -d'-' -f1)"]
